# Permalinks
permalink:           pretty

# Setup
title:               Nathan Maton - Coach, Angel investor, Outdoor lover
# tagline:             Portfolio
url:                 http://nathanmaton.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nathan Maton
  url:               https://twitter.com/nathanmaton
  email:             n/a

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/nathanmaton.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:
  Coaching: '/coaching'
  About: '/about'
  Family band: '/familyband'
  Climbing: '/climbing'
  My better half: '/jane'
#  Portfolio: '/portfolio'
  # Archive: '/archive'
  # Feed: '/index.html'
